SverigesSandareamatorer/SSA-Akademin

- koncept/chapter3-6.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
- koncept/chapter4-2.tex
- koncept/chapter4-3.tex
- koncept/chapter4-9.tex
- koncept/chapter5-1.tex
- koncept/chapter5-2.tex
- koncept/chapter6-1.tex
- koncept/chapter6-3.tex
- koncept/chapter6-6.tex
- koncept/chapter7-3.tex
- koncept/chapter7-6.tex
- koncept/chapter9-3.tex
- koncept/chapter9-4.tex
Gör så att många angivelser av intervall följer rekommendationen: inga mellanslag och (kort) tankstreck som avdelare.
> Fixa intervallangivelser

- koncept/chapter10-1.tex
Rätta att icke-kompletta URL:er var uppmärkta som URL:er. Därmed gick de inte att klicka på i den genererade PDF:en.
> Rätta URL:er

- koncept/appendix-e.tex
- koncept/chapter1-8.tex
- koncept/chapter2-3.tex
- koncept/chapter3-1.tex
- koncept/chapter3-4.tex
- koncept/chapter3-9.tex
- koncept/chapter4-9.tex
- koncept/chapter6-1.tex
- koncept/chapter7-3.tex
- koncept/chapter8-1.tex
- koncept/chapter8-2.tex
Innan procenttecken har man ett (hårt) mellanslag.
> Lägg till hårt mellanslag innan procenttecken

- koncept/chapter11-4.tex
Att ha rätt modulation är viktigt när man använder de nödfrekvenser för telefoni som anges i boken.
> Förtydligande av nödfrekvenser

- koncept/chapter1-6.tex
Med tanke på hur stor del av radioapparaterna som tillverkats av Japanska företag kan det vara allmänbildning att veta att (halva) Japan använder 60 Hz i elnätet.
> Lägg till Japan som 60 Hz:are

- .gitignore
- koncept/chapter1-1.tex
- koncept/chapter2-2.tex
- koncept/chapter2-7.tex
- koncept/chapter3-1.tex
- koncept/chapter3-2.tex
Some of the wrapfigure images was overflowing the text. The detailed layout should be left
to the finishing typesetting, so I converted most of them to normal figure environments.
> Fixed some layout problems with images

- Makefile
- koncept/chapter1-1.tex
Also, included is an example of adding indexed words that is not indexed automatically.
> Index now works

- koncept-larobok.tex
- koncept-online.tex
- koncept-refbok.tex
- koncept-tryck.tex
- koncept.tex
Pixel är inte en av de ursprungliga LaTeX-enheterna. När värdet ändå är 0 så kan man byta till _punkter_ för att undvika kompileringsfel.
> Ändra till punkter istället för pixel

- koncept/chapter13-5.tex
Exempel på allmänt anrop var inbäddat i brödtext medans exempel på riktat  anrop var utbrytet till egna rader för bättre läsbarhet.
Allmänt anrop är nu på egna rader och följer samma formatering som för riktat anrop då jag anser läsbarheten blir bättre.
Har även tagit bort "." (punkt/stopptecken) som förekom i vissa fall efter Kom.
Då texterna syftar till att vara exempel på vad man ska sända (telefoni eller CW) är punkten i sammanhanget missvisande då det inte är avsett att man ska sända/uttala tecknet.
- Exempel på allmänt anrop på egna rader för bättre läsbarhet
- Tagit bort missvisande "." (punkt/stopptecken) efter "Kom"
Fixes #328
> Mer konsekvent formatering av anropsexempel

- texifiering.md
Justera formatregeln om förkortningar så att man ska använda den utskrivna formen i löptext, men kan använda förkortningen i parenteser och tabeller där det är en klar fördel med kortare text.
Jag gör en egen PR av den här ändringen så andra kan tycka till.
> Villkora formatregeln om förkortningar

- CHANGELOG.md
- koncept/matte.tex
- Förändringar
- Bytter felaktig användning av ordet "decimal" till "siffra".
- Förtydligar vad oktal och hexadecimal form är för något.
- Ändrar till utskrivna siffor istället för siffror.
- I enlighet med texifiering.md .31
- Extra radbrytning i enlighet med texifiering.md .5
Fixes #365
> Uppdaterat språk i avsnittet "Binära tal" i kapitlet "Matematik".

- CHANGELOG.md
- koncept/matte.tex
- Ändrar rubrik till "Ekvation med en obekant" från "Exempel med .."
Då nya koncept införs i avsnittet blir det väldigt konstigt att använda "Exempel" i rubriken.
Finns dessutom underrubriker med "Exempel" också vilket ger exempel i exempel vilket inte
känns helt motiverat.
Lade till en förklarande text i första att koncepten förklaras genom ett exempel.
Hade ursprungligen rubriken "Lösning av ekvation med en obekant" rubriken blir dock då så
lång att den sväller ut i sidhuvudet.
Mindre ändringar
- Ändrar 1/2 till en/två i rubrik i Bilaga B, matematik
- Ändrar förkortningen s.k. till så kallad(e) i Bilaga B, matematik
> Språkliga ändringar i Bilaga B, Matematik

- CHANGELOG.md
- koncept/appendix-j.tex
- Ändrat O till Q i rapportkoder för kommeriell sjö och luftradiotrafik.
OCR-fel?
> Ändrat O till Q i rapportkoder för kommeriell sjö och luftradiotrafik.

- koncept.bib
- koncept/appendix-e.tex
- koncept/chapter13-1.tex
- Har lagt till URL i ITU-RR i .bib så den pekar mot ITU websida
- Har ändrat de två referenserna till ITU-RR-Appendices att peka mot ITU-RR istället
- Uppdaterade referensen till ITU-RR appendix 1 att följa samma format som ref till appendix 14 (att inkludera "appendix _" i \cite) (stilregel 25)
> Saknad referens till ITU-RR appendix ompekad till ITU-RR

- .travis.yml
- Dockerfile
Detta är ungefär hälften av vad jag pratade om [här](https://github.com/SverigesSandareamatorer/SSA-Akademin/issues/446#issuecomment-423767683).  Dockerfilen bygger nu på Alpine istället för Debian, eftersom Alpine containrar blir mindre och byggs snabbare.  Sedan används den containern för att bygga PDF:en av Travis CI.
> Bygg i Docker container i Travis CI

- Dockerfile
-  Lade till paketet sshpass på grund av detta fel:
```
sshpass -e scp koncept.pdf ${FTP_USER}@${FTP_SERVER}:${FTP_FOLDER}koncept-pdf/koncept.$(cat VERSION.txt)+b$(printf "%04d" "${TRAVIS_BUILD_NUMBER}").${TRAVIS_COMMIT:0:7}.pdf
The program 'sshpass' is currently not installed. To run 'sshpass' please ask your administrator to install the package 'sshpass'
```
> Dockerfile: lade till paketet sshpass

- koncept.tex
På många sidor är det något ord som inte får plats i spalten. Jag föreslår att vi ger paketet microtype lite större spelrum att justera texten. Efter experimenterande har jag kommit fram till innehållet i den här PR:n men kom gärna med egna förslag och åsikter. I [manualen för microtype](https://ftp.acc.umu.se/mirror/CTAN/macros/latex/contrib/microtype/microtype.pdf) hittar man lite om valen man kan göra.
> Större spelrum för microtype att justera texten

- koncept/appendix-mattenheter.tex
- koncept/common.tex
- koncept/foreword.tex
fixar siunitx varningar och problem med enhetslösa prefix i appendix mattenheter fixar dubbla förord
- Förändringar
> fixar siunitx varningar

- .github/workflows/bygg.yml
- .gitignore
- Makefile
- Ett uppdaterings-kommando till autobyggena så att de inte går sönder om filerna ändrats på paketservrarna.
- Det finns rapporter i Makefile som nu används och resultatet sparas som en artefakt.
> Fixa trasigt bygge och spara rapporter

- .github/workflows/bygg.yml
- .gitignore
- Makefile
Lägger till en ny rapport som visar vilka kodrader som är längre än 80 tecken.
> Lägg till rapport för rader längre än 80 tecken

- koncept.tex
Efter att ha rådfrågat kompetens på området har jag fått rekommendationen att sätta circitikz till att använda fältriktningen `nooldvoltagedirection`. Fix #573
> Sätt riktningen på fältpilar i circuitikz

- .github/workflows/bygg.yml
- CHANGELOG.md
- Makefile
Märk EPUB-generering som experimentell då den inte fungerar tillförlitligt än. Relaterad till #55. Fix #648.
> Märk EPUB-generering som experimentell

- koncept/tryckort.tex
Hej! Jag fick precis hem min kopia av koncept och noterade en liten miss på första sidan!
- Två siffror hade bytt plats på ISBN i koncept, tryckkort.tex
> Fixa typo i ISBN på tryckkort.tex

- koncept/chapter2-7.tex
Denna åtgärdar att två ekvationer i 2.7 stoppade genereringen av EPUB. Det kan ha varit att `align*` inte funkar om den bara har en rad att _aligna_.
Detta stänger inget ärende men är ett steg på vägen mot #55
> Fixa ekvationer som stoppar EPUB-genereringen

- CHANGELOG.md
- Makefile
- koncept/appendix-morsesignalering.tex
- koncept/inkludera-appendix.tex
- koncept/inkludera-kapitel.tex
- Flytta Morsesignalering till bilaga för att tydliggöra att den inte är del av det de obligatoriska kunskaperna för certifikatprovet. Fix #686
> Flytta Morsesignalering till bilaga

- CHANGELOG.md
- koncept/chapter1-10.tex
- koncept/chapter1-8.tex
- koncept/chapter11-1.tex
- koncept/chapter2-5.tex
- koncept/chapter3-10.tex
- koncept/chapter3-2.tex
- koncept/chapter3-7.tex
- koncept/chapter4-1.tex
- koncept/chapter5-8.tex
- koncept/chapter6-1.tex
- koncept/chapter6-2.tex
- koncept/chapter8-3.tex
- koncept/chapter8-7.tex
- koncept/chapter9-1.tex
- koncept/chapter9-2.tex
- Meddela engelska förkortningar med hjälp av kommatecken istället för dubbelparentes. Fix #524
> Inga dubbelparentes vid engelska förkortningar

- koncept/chapter2-5.tex
- koncept/chapter2-6.tex
bilderna 2.16 2.17 2.18 och 2.23 har ersatts med kodade figurer
- Förändringar
> Ersatt fyra bilder i kapitel två med hjälp av circuitikz

- CHANGELOG.md
- Makefile
- koncept.tex
- koncept/inkludera-appendix.tex
- koncept/litteratur.tex
- Flytta litteraturförteckningen till mellan kapitel och bilagor. Se #645
> Flytta litteraturförteckningen till mellan kapitel och bilagor

- .github/rungs.txt
- .github/workflows/bygg.yml
Lägg till byggsteg med buggkorrigeringar för EPUB. Relaterad till #55
> Lägg till byggsteg med buggkorrigeringar för EPUB

- .editorconfig
- CHANGELOG.md
- koncept/appendix-frekvensplan.tex
- Ta bort primär/sekundär status från frekvensplan m.m. Fix #724
> Ta bort primär/sekundär status från frekvensplan m.m.
