- BUILD.md
- README.md
BUILD.md innehåller allt för att hämta hem, installera beroenden och köra projektet.
> Lagt till fil BUILD.md som beskriver hur man bygger projektet och installerar beroenden

- introduction.tex
- koncept/appendix-g.tex
- koncept/appendix-i.tex
- koncept/chapter11-6.tex
- koncept/chapter2-2.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
Rätta några tecken som blivit "l" i OCR.
> Rätta "l" (OCR)

- koncept-alpha.tex
- koncept-larobok.tex
- koncept-refbok.tex
- koncept.tex
Ändra adress och telefonnummer för att följa [UPU:s rekommendation](http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/sweEn.pdf) samt [E.123](https://www.itu.int/rec/T-REC-E.123-200102-I/).
> Rätta adress och telefonnummer

- koncept/chapter1-7.tex
- koncept/chapter2-10.tex
- koncept/chapter2-2.tex
- koncept/chapter2-3.tex
Kelvin är inte en enhet som anges i grader.
> Rätta kelvin

- koncept/appendix-a.tex
- koncept/appendix-d.tex
- koncept/appendix-e.tex
- koncept/chapter1-1.tex
- koncept/chapter1-2.tex
- koncept/chapter1-5.tex
- koncept/chapter1-6.tex
- koncept/chapter1-8.tex
- koncept/chapter1-9.tex
- koncept/chapter11-5.tex
- koncept/chapter2-1.tex
- koncept/chapter3-3.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
- koncept/chapter3-9.tex
- koncept/chapter4-2.tex
- koncept/chapter4-5.tex
- koncept/chapter4-8.tex
- koncept/chapter4-9.tex
- koncept/chapter7-4.tex
- koncept/chapter7-6.tex
- koncept/chapter9-3.tex
- koncept/emf.tex
- matte.tex
"Till exempel" förkortas som t.ex. (eller t ex).
> Ändra till t.ex.

- koncept/appendix-j.tex
- koncept/chapter1-6.tex
- koncept/chapter10-1.tex
- koncept/chapter11-5.tex
- koncept/chapter3-7.tex
- koncept/chapter4-8.tex
- koncept/chapter6-1.tex
- koncept/chapter7-1.tex
- koncept/chapter7-5.tex
- koncept/chapter8-1.tex
- koncept/chapter8-2.tex
> Korrektur m.m.

- koncept/chapter1-1.tex
- koncept/chapter1-5.tex
- koncept/chapter1-8.tex
- koncept/chapter10-2.tex
- koncept/chapter11-4.tex
- koncept/chapter14-1.tex
- koncept/chapter2-10.tex
- koncept/chapter2-3.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
- koncept/chapter4-9.tex
- koncept/chapter6-3.tex
- koncept/chapter6-6.tex
- koncept/chapter7-1.tex
- koncept/chapter7-2.tex
- koncept/chapter7-5.tex
- koncept/chapter7-6.tex
- koncept/chapter8-1.tex
- koncept/chapter8-2.tex
- koncept/morse.tex
- matte.tex
> Ännu mera korrektur

- Makefile
Jag fixar så att...
- LaTeXML genererar en webb-sida per sektion så att man inte behöver ladda hela boken
- stilen på sidan gör det lättare att läsa
- det finns en navigationsmeny som gör det lätt att förflytta sig
> LaTeXML generering av sidor (bättre style, sidor uppdelade efter kapitel)

- koncept/emf.tex
> Korrekturändringar

- koncept/chapter6-1.tex
- koncept/chapter6-4.tex
- koncept/chapter6-5.tex
Lite korrekturändringar efter mötet 2017-08-30.
> Yagiantenn

- koncept/appendix-i.tex
> Formatera Appendix I

- .travis.yml
Förbereder lite för Travis CI. @fnadde42 (eller någon annan) får gärna kopiera ur innehållet istället för att dra in den direkt. Relaterad till #6.
> Lägg till .travis.yml

- koncept/chapter1-8.tex
- koncept/chapter1-9.tex
- koncept/chapter2-7.tex
- koncept/chapter6-6.tex
- koncept/chapter7-6.tex
Gör inte merge än! Använder denna PR för att kunna testköra Travis.
> Åtgärda LaTeX-fel

- .travis.yml
- Makefile
Försöker undvika meddelandena
```
LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.
```
> Kör LaTeX en extra gång i vissa fall

- koncept/appendix-c.tex
- koncept/chapter1-5.tex
- koncept/chapter1-8.tex
- koncept/chapter11-5.tex
- koncept/chapter12-3.tex
- koncept/chapter14-1.tex
- koncept/chapter3-3.tex
- koncept/chapter3-4.tex
- koncept/chapter3-5.tex
- koncept/chapter3-6.tex
- koncept/chapter4-2.tex
- koncept/chapter7-6.tex
- koncept/chapter9-2.tex
Korrekturändringar och en annan ändring.
> Korrekturändringar 27/9 -17

- koncept/common.tex
> Lägg till PDF-metadata

- koncept/appendix-e.tex
- koncept/chapter10-2.tex
- koncept/chapter14-1.tex
- koncept/chapter2-1.tex
- koncept/chapter2-2.tex
- koncept/chapter2-4.tex
- koncept/chapter3-1.tex
- koncept/chapter3-3.tex
- koncept/chapter3-6.tex
- koncept/chapter3-9.tex
- koncept/chapter6-1.tex
- koncept/chapter7-2.tex
- koncept/chapter8-2.tex
- koncept/emf.tex
> Korrekturändringar 4/10 -17

- koncept/chapter7-6.tex
> Gör en punktlista av en lista

- .travis.yml
> Säkra upp överföring till server

- koncept/chapter1-10.tex
- koncept/chapter1-8.tex
- koncept/chapter3-1.tex
- koncept/chapter3-4.tex
Ändra lite i sakregistret. Relaterad till #158
> Ändringar i sakregistret

- .travis.yml
~~Detta är bara en test PR~~
Drar in för att kunna se vilka värden `$TRAVIS_EVENT_TYPE` antar för att se om man kan förhindra länkskapande mot permalänken `koncept.pdf`. Om triggade ombyggen gör om länken så kan den helt plötsligt peka på en gammal version (den man byggde om).
> Testar att se vilken typ bygge är

- koncept.bib
- koncept/chapter16-1.tex
Efter diskussion lade jag till morse-standarden från ITU-R.
> Lade till Morse-standard.

- koncept/common.tex
Test för att se om lmodern löser problemen med tecken #223
> test med package lmodern

- koncept/chapter1-1.tex
- koncept/chapter12-1.tex
- koncept/chapter12-2.tex
- koncept/chapter12-3.tex
Justerat elsäkerhetsavsnittet efter samråd med cj/pts.
Fixat ett stavfel.
Förtydligat effektformler  #231
> Justeringar av text och formler

- koncept/chapter1-1.tex
Fixes #247
EDIT: Sätter så denna PR stänger ärendet //fnadde42
> lagt till 10 potens

- texifiering.md
Tiny Tiny PR
Apropå -> https://github.com/SverigesSandareamatorer/SSA-Akademin/issues/255#issuecomment-340677577
> Lade till regel om att förkortningar ska skrivas ut

- Makefile
Lägg gärna till fler mål i den här listan och beskriv vad dom gör. Vissa mål är ju inte gjorda att köras direkt utan indirekt genom beroenden men det vet ni bättre än mig.
> Hjälpmeny ska visas om make körs utan argument

- docs/PULL_REQUEST_TEMPLATE.md
- Föreslagen Pull Request Template
- ~~Följer stilmallen specifierad i [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)~~ Ej applicerbar
- ~~Förändringar bygger utan fel lokalt och på byggserver~~ Ej applicerbar
- ~~Förändringar (om signifikanta) införd i [`CHANGELOG.md`](../blob/master/CHANGELOG.md)~~ Ej applicerbar
Fixes #33
> Pull Request Template

- koncept-alpha.tex
- koncept/chapter1-1.tex
- koncept/chapter1-4.tex
- koncept/chapter1-5.tex
- koncept/chapter1-7.tex
- koncept/chapter1-8.tex
- koncept/chapter12-2.tex
- koncept/chapter14-2.tex
- koncept/chapter2-2.tex
- koncept/chapter2-5.tex
- koncept/chapter2-9.tex
- koncept/chapter3-4.tex
- koncept/chapter3-5.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
- koncept/chapter5-2.tex
- koncept/chapter7-4.tex
- koncept/chapter8-3.tex
- koncept/chapter8-5.tex
- Ändra alla 'såsom' till 'så som'
- Det låter extremt gammalmodigt att skriva orden ihop (var förvånad att det ens var ett ord i SAOL)
> Ändra alla 'såsom' till 'så som'

- koncept/chapter8-6.tex
> Rättat upphuggen mening

- koncept-alpha.tex
- koncept/chapter1-1.tex
- koncept/chapter1-4.tex
- koncept/chapter1-5.tex
- koncept/chapter1-7.tex
- koncept/chapter1-8.tex
- koncept/chapter12-2.tex
- koncept/chapter14-2.tex
- koncept/chapter2-2.tex
- koncept/chapter2-5.tex
- koncept/chapter2-9.tex
- koncept/chapter3-4.tex
- koncept/chapter3-5.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
- koncept/chapter5-2.tex
- koncept/chapter7-4.tex
- koncept/chapter8-3.tex
- koncept/chapter8-5.tex
- Först och främst, återställ kaoset jag skapade igår.
- Nummer två; vi ska se till att "såsom" och "så som" används i korrekt sammanhang. Var lite snabb förra PR:en att dra alla över en kam.
Allt eftersom vi hittar ställen där vi *faktiskt* ska byta ut ett *såsom* så uppdaterar jag denna PR.
> Korrekt användning av 'så som' och 'såsom'

- koncept/chapter1-1.tex
- koncept/chapter1-8.tex
- koncept/chapter2-1.tex
- koncept/chapter2-10.tex
- koncept/chapter3-1.tex
- texifiering.md
> Korrekturändringar 7/11 -17

- koncept/chapter13-5.tex
> Fixat stavfel "aanropssignalen"

- koncept/chapter1-9.tex
> Ersatt "utbildats" med "utvecklats"

- .github/PULL_REQUEST_TEMPLATE.md
> Lägger till check för om författaren är redo för merge

- koncept/chapter1-8.tex
- koncept/chapter3-1.tex
- koncept/chapter3-9.tex
- koncept/chapter6-1.tex
> Språkkorrigeringar kapitel 1.8 samt delar av kap 3.1, 3.9 och 6.1 #130

- koncept.bib
- koncept/chapter1-9.tex
- koncept/chapter3-1.tex
> Justering av formler 1.9 och 3.1.8 #286

- koncept/chapter1-3.tex
- koncept/chapter1-6.tex
- koncept/chapter1-8.tex
- koncept/chapter2-10.tex
- koncept/chapter2-2.tex
- koncept/chapter2-3.tex
- koncept/chapter2-4.tex
- koncept/chapter3-1.tex
- koncept/chapter3-5.tex
- koncept/chapter3-9.tex
- koncept/chapter9-1.tex
- koncept/chapter9-2.tex
> Språkkorrigeringar kapitel 1.8

- .editorconfig
- texifiering.md
Vi börjar nu bli en ett antal personer som hackar på samma kod. Att hålla sig till en kodstil är då bra. Med en [.editorconfig](http://editorconfig.org) i arbetsmappen kan texteditorn (vissa) automatiskt ställa in ett antal parametrar för hur filen ska vara. Jag har kollat runt lite i filerna och tagit vad som verkar vara de facto-standarden som utgångsläge.
Ingen.
> En första kodstil

- koncept/chapter16-1.tex
- Rättat bildtext 16.5
Fixes #297
> Rättat bildtext för morsealfabetet

- koncept/chapter8-7.tex
Jag är ganska säker på att _fresnel_ stavas just så men rätta mig om jag har fel.
> freznel -> fresnel

- koncept/chapter5-8.tex
> Stavningskorrigering 5.8.8 subton

- koncept/chapter12-2.tex
- koncept/chapter3-2.tex
> Fixes #301

- koncept/chapter12-2.tex
- koncept/chapter8-7.tex
- koncept/chapter9-2.tex
- Förändringar
Fixes #306 
Fixes #308
> Fixes #306 #308

- koncept/chapter16-1.tex
- Förändringar
Fixes # 299
Fixes # 300
> Fixat 2 issues gällande CW

- koncept.tex
> Fixes #251 #309

- koncept/chapter1-10.tex
- koncept/chapter1-8.tex
- koncept/chapter1-9.tex
- koncept/chapter13-5.tex
- koncept/chapter2-10.tex
- koncept/chapter3-10.tex
- koncept/chapter9-2.tex
> Språkkorrigeringar kap 1.13 och 3.10

- koncept/chapter9-2.tex
> mätinstrument fixes #307

- koncept/chapter1-1.tex
>  förtydligat text om halvledare Fixes #321

- koncept/chapter1-8.tex
> Bytt namn på 1.8.17 Fixes #324

- koncept/chapter1-1.tex
- koncept/chapter3-6.tex
> ändringar 3.6.1 efter feedback

- koncept/chapter3-6.tex
> 3.6.1 textjustering efter feedback från fnadde42

- koncept/chapter1-3.tex
- fixat särskrivning och böjning 
Fixes #342
> Fixat särskrivning "omkring liggande"

- koncept/chapter1-8.tex
- koncept/chapter2-1.tex
- koncept/chapter2-2.tex
- koncept/chapter2-3.tex
> Språkkorrigeringar i kapitel 2.1 - 2.3

- koncept/chapter1-4.tex
- koncept/chapter2-4.tex
- koncept/chapter2-5.tex
> Språkkorrigeringar kapitel 2.4–2.5

- koncept/chapter1-1.tex
- koncept/chapter1-8.tex
- koncept/chapter10-3.tex
- koncept/chapter12-2.tex
- koncept/chapter12-3.tex
- koncept/chapter13-2.tex
- koncept/chapter15-1.tex
- koncept/chapter2-1.tex
- koncept/chapter2-2.tex
- koncept/chapter2-3.tex
- koncept/chapter2-4.tex
- koncept/chapter2-9.tex
- koncept/chapter3-1.tex
- koncept/chapter3-10.tex
- koncept/chapter3-2.tex
- koncept/chapter3-4.tex
- koncept/chapter3-7.tex
- koncept/chapter5-8.tex
- koncept/chapter5-9.tex
- koncept/chapter6-1.tex
- koncept/chapter7-1.tex
- koncept/chapter7-6.tex
- koncept/chapter8-1.tex
- koncept/chapter8-2.tex
- koncept/chapter8-3.tex
- koncept/chapter8-6.tex
- koncept/chapter8-7.tex
- koncept/chapter9-1.tex
- koncept/chapter9-2.tex
- koncept/part3.tex
Diverse korrekturändringar 30 november 2017.
> Korrekturändringar 30/11 -17

- koncept/chapter1-10.tex
- koncept/chapter1-4.tex
- koncept/chapter1-5.tex
- koncept/chapter1-6.tex
- koncept/chapter1-7.tex
- koncept/chapter1-8.tex
- koncept/chapter1-9.tex
- koncept/chapter11-1.tex
- koncept/chapter12-2.tex
- koncept/chapter12-3.tex
- koncept/chapter13-4.tex
- koncept/chapter13-5.tex
- koncept/chapter7-6.tex
- koncept/chapter8-1.tex
- koncept/chapter9-1.tex
Blandade korrekturändringar 1 december 2017.
> Korrekturändringar 1/12 -17

- koncept/chapter2-10.tex
- koncept/chapter2-6.tex
- koncept/chapter2-7.tex
- koncept/chapter2-8.tex
- koncept/chapter2-9.tex
- koncept/chapter7-6.tex
> Språkkorrigeringar mm kapitel 2.6 - 2.11.

- koncept/chapter1-1.tex
- koncept/chapter2-4.tex
- koncept/chapter2-5.tex
- koncept/chapter2-7.tex
- koncept/chapter3-6.tex
> Omarbetad text om halvledare 1.1.4

- koncept/appendix-a.tex
- koncept/appendix-i.tex
- koncept/appendix-j.tex
- koncept/chapter1-5.tex
- koncept/chapter1-7.tex
- koncept/chapter1-8.tex
- koncept/chapter12-2.tex
- koncept/chapter15-1.tex
- koncept/chapter2-4.tex
- koncept/chapter2-6.tex
- koncept/chapter2-9.tex
- koncept/chapter3-2.tex
- koncept/chapter3-4.tex
- koncept/chapter3-6.tex
- koncept/chapter3-7.tex
- koncept/chapter4-1.tex
- koncept/chapter6-1.tex
- koncept/chapter6-2.tex
- koncept/chapter7-3.tex
- koncept/chapter7-5.tex
- koncept/chapter7-6.tex
- koncept/chapter8-1.tex
- koncept/chapter8-5.tex
- koncept/chapter9-2.tex
Blandade korrekturändringar 2 december 2017.
> Korrekturändringar 2/12 -17

- koncept/chapter13-5.tex
- koncept/chapter14-3.tex
> lagt till second operator som nytt 13.5.3 Fixes#352

- CHANGELOG.md
- koncept/appendix-a.tex
- Förtydligande av prefixs syfte.
Fixes #367
> Förtydligande av prefixs syfte.

- koncept/chapter2-10.tex
> Omformulering kapitel 2.11.4

- CHANGELOG.md
- koncept/matte.tex
- Förändringar
Saknades tal och felaktig uträkning i formeln.
> Formel rättad i avsnittet "Exempel med 2 obekanta" i kapitlet "Matematik".

- koncept/appendix-a.tex
- koncept/appendix-e.tex
- koncept/appendix-i.tex
- koncept/chapter1-1.tex
- koncept/chapter1-4.tex
- koncept/chapter1-8.tex
- koncept/chapter10-1.tex
- koncept/chapter10-4.tex
- koncept/chapter12-1.tex
- koncept/chapter12-2.tex
- koncept/chapter12-4.tex
- koncept/chapter14-2.tex
- koncept/chapter3-2.tex
- koncept/chapter3-3.tex
- koncept/chapter3-4.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
- koncept/chapter5-3.tex
- koncept/chapter6-1.tex
- koncept/chapter7-1.tex
- koncept/chapter7-6.tex
- koncept/chapter8-1.tex
- koncept/chapter8-3.tex
- koncept/chapter8-4.tex
- koncept/chapter9-1.tex
Blandade korrekturändringar 5 december 2017.
> Korrekturändringar 5/12 -17

- koncept/chapter1-1.tex
- koncept/chapter1-3.tex
- koncept/chapter1-4.tex
- koncept/chapter1-7.tex
- koncept/chapter1-9.tex
- koncept/chapter10-2.tex
- koncept/chapter10-3.tex
- koncept/chapter12-2.tex
- koncept/chapter13-5.tex
- koncept/chapter14-1.tex
- koncept/chapter15-1.tex
- koncept/chapter16-1.tex
- koncept/chapter2-5.tex
- koncept/chapter2-9.tex
- koncept/chapter3-4.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
- koncept/chapter3-9.tex
- koncept/chapter5-3.tex
- koncept/chapter5-4.tex
- koncept/chapter5-8.tex
- koncept/chapter5-9.tex
- koncept/chapter6-2.tex
- koncept/chapter7-1.tex
- koncept/chapter7-4.tex
- koncept/chapter7-6.tex
- koncept/chapter8-1.tex
- koncept/chapter8-2.tex
- koncept/chapter8-6.tex
- koncept/chapter9-2.tex
Blandade korrekturändringar 8 december 2017.
> Korrekturändringar 8/12 -17

- Dockerfile
- Makefile
> Fixa så att koncept.pdf går att bygga i Docker-container

- koncept/appendix_n.tex
> Prefixomvandlingstabell skapad #357

- koncept/appendix_n.tex
> hoppsan, bytt ampere mot farad #357

- Makefile
- handouts/prefix.tex
- koncept/appendix-n.tex
- koncept/koncept-core.tex
- Prefixomvandlingstabell
Fixes #357
> Prefixomvandlingstabell

- koncept.bib
- koncept/chapter13-5.tex
- koncept/chapter14-3.tex
> Ny text om tystnadsplikt och kryptering Fixes #364

- koncept/appendix-a.tex
- koncept/appendix-d.tex
- koncept/appendix-f.tex
- koncept/appendix-h.tex
- koncept/appendix-j.tex
- koncept/appendix-l.tex
- koncept/chapter1-8.tex
- koncept/chapter10-4.tex
- koncept/chapter12-2.tex
- koncept/chapter16-1.tex
- koncept/chapter3-1.tex
- koncept/chapter3-2.tex
- koncept/chapter3-3.tex
- koncept/chapter3-4.tex
- koncept/chapter3-6.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
- koncept/chapter3-9.tex
- koncept/chapter5-2.tex
- koncept/chapter6-1.tex
- koncept/chapter6-2.tex
- koncept/chapter7-4.tex
- koncept/chapter8-6.tex
- koncept/chapter9-1.tex
- koncept/chapter9-2.tex
Blandade korrekturändringar 25 december 2017.
> Korrekturändringar 25/12 -17

- koncept/chapter3-1.tex
- koncept/chapter3-10.tex
- koncept/chapter3-3.tex
- koncept/chapter3-4.tex
- koncept/chapter3-5.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
- koncept/chapter3-9.tex
Blandade korrekturändringar i kapitel 3.
> Korrektur kap 3

- koncept/chapter3-4.tex
- koncept/chapter3-5.tex
- koncept/chapter3-6.tex
- koncept/chapter3-8.tex
- koncept/chapter4-1.tex
- koncept/chapter5-2.tex
- koncept/chapter5-3.tex
- koncept/chapter5-8.tex
- koncept/chapter6-2.tex
- koncept/chapter7-1.tex
- koncept/chapter7-3.tex
- koncept/chapter7-6.tex
- koncept/chapter8-1.tex
- koncept/chapter8-7.tex
- koncept/chapter9-2.tex
> dvs. och resp. åtgärdas

- koncept/appendix-d.tex
- koncept/appendix-e.tex
- koncept/appendix-g.tex
- koncept/appendix-j.tex
- koncept/chapter10-1.tex
- koncept/chapter10-3.tex
- koncept/chapter11-1.tex
- koncept/chapter12-1.tex
- koncept/chapter12-2.tex
- koncept/chapter3-3.tex
- koncept/chapter3-4.tex
- koncept/chapter3-7.tex
- koncept/chapter5-2.tex
- koncept/chapter5-8.tex
- koncept/chapter5-9.tex
- koncept/chapter6-2.tex
- koncept/chapter7-1.tex
- koncept/chapter7-3.tex
- koncept/chapter7-5.tex
- koncept/chapter7-6.tex
- koncept/chapter8-3.tex
- koncept/chapter8-4.tex
- koncept/chapter8-5.tex
- koncept/chapter8-6.tex
- koncept/chapter9-1.tex
- koncept/chapter9-2.tex
Blandade korrekturändringar 3 januari 2017.
> Korrekturändringar 3/1 -17

- koncept/appendix-f.tex
- koncept/chapter1-6.tex
- koncept/chapter10-1.tex
- koncept/chapter10-2.tex
- koncept/chapter12-2.tex
- koncept/chapter13-5.tex
- koncept/chapter15-1.tex
- koncept/chapter3-4.tex
- koncept/chapter3-7.tex
- koncept/chapter5-4.tex
- koncept/chapter5-9.tex
- koncept/chapter7-3.tex
- koncept/chapter7-5.tex
- koncept/chapter8-2.tex
- koncept/chapter8-3.tex
- koncept/chapter8-5.tex
- koncept/chapter9-1.tex
- koncept/chapter9-2.tex
Blandade korrekturändringar 4 januari 2018.
> Korrekturändringar 4/1 -18

- koncept/appendix-g.tex
- koncept/chapter10-3.tex
- koncept/chapter11-1.tex
- koncept/chapter12-1.tex
- koncept/chapter13-5.tex
- koncept/chapter8-3.tex
- koncept/chapter8-5.tex
Blandade korrekturändringar 14 januari 2018.
> Korrekturändringar 14/1 -18

- koncept/appendix-d.tex
- koncept/appendix-e.tex
- koncept/appendix-f.tex
- koncept/appendix-g.tex
- koncept/chapter13-4.tex
- koncept/chapter13-5.tex
- koncept/chapter16-1.tex
- koncept/chapter3-7.tex
- koncept/chapter3-9.tex
- koncept/chapter5-3.tex
- koncept/chapter5-9.tex
- koncept/chapter8-5.tex
Blandade korrekturändringar 16 januari 2018.
> Korrekturändringar 16/1 -18

- koncept/chapter12-3.tex
- koncept/chapter14-3.tex
- koncept/chapter16-1.tex
- koncept/chapter7-5.tex
- koncept/chapter7-6.tex
- koncept/chapter8-2.tex
- koncept/chapter8-5.tex
- koncept/chapter8-7.tex
- koncept/chapter9-2.tex
Blandade korrekturändringar 18 januari 2018.
> Korrekturändringar 18/1 -18

- koncept/chapter3-1.tex
> Korrigeringar av språk och formler i kapitel 3.1.11 - 3.1.19

- koncept/appendix-c.tex
- koncept/appendix-f.tex
- koncept/appendix-l.tex
- koncept/chapter12-2.tex
- koncept/chapter13-5.tex
- koncept/chapter3-1.tex
- koncept/chapter3-10.tex
- koncept/chapter3-2.tex
- koncept/chapter3-4.tex
- koncept/chapter3-6.tex
- koncept/chapter5-9.tex
- koncept/chapter6-2.tex
- koncept/chapter8-5.tex
- koncept/foreword.tex
Blandade korrekturändringar 6 februari 2018.
Fixes #406
> Korrekturändringar 6/2 -18

- koncept/chapter3-2.tex
> Korrigeringar kapitel 3.2

- .editorconfig
- BUILD.md
- CHANGELOG.md
- README.md
- koncept.bib
- koncept/chapter3-1.tex
- koncept/chapter3-9.tex
- texifiering.md
Blandade korrekturändringar 11 februari 2018.
> Korrekturändringar 11/2 -18

- koncept/appendix-f.tex
- koncept/chapter10-3.tex
- koncept/chapter13-4.tex
- koncept/chapter13-5.tex
- koncept/chapter5-2.tex
- koncept/chapter8-6.tex
- koncept/foreword.tex
- koncept/preface.tex
Blandade korrekturändringar 12 februari 2018.
> Korrekturändringar 12/2 -18

- koncept/chapter1-10.tex
- koncept/chapter3-3.tex
> Språkkorrigeringar kapitel 3.3 samt fix kapitel 1.13.3 #330

- koncept/appendix-f.tex
- koncept/appendix-h.tex
- koncept/appendix-l.tex
- koncept/chapter13-2.tex
- koncept/chapter13-3.tex
- koncept/chapter13-5.tex
- koncept/chapter13-6.tex
- koncept/chapter14-1.tex
- koncept/chapter14-3.tex
- koncept/chapter15-1.tex
- koncept/chapter3-8.tex
- koncept/chapter8-5.tex
- koncept/chapter9-2.tex
Korrekturändringar som Adam Marmbrandt skickat in via epost.
> Korrekturändringar från Adam Marmbrandt

- koncept/chapter3-8.tex
> 3-8 mjuk referens till kap 5 och 6 inskriven

- koncept/chapter10-4.tex
- koncept/chapter11-1.tex
- koncept/chapter12-2.tex
- koncept/chapter12-3.tex
- koncept/chapter13-5.tex
- koncept/chapter14-2.tex
- koncept/chapter16-1.tex
- koncept/chapter2-5.tex
- koncept/chapter3-4.tex
- koncept/chapter3-7.tex
- koncept/chapter6-1.tex
- koncept/chapter7-1.tex
- koncept/chapter7-5.tex
- koncept/chapter7-6.tex
- koncept/chapter8-1.tex
- koncept/chapter8-6.tex
- koncept/chapter9-2.tex
Blandade korrekturändringar 17 mars 2018. Samt två tillägg i sakregistret.
> Korrekturändringar 17/3 -18

- koncept.bib
- koncept/chapter10-1.tex
- koncept/chapter10-2.tex
- koncept/chapter10-3.tex
- koncept/chapter10-4.tex
> Översyn EMC

- koncept/appendix-e.tex
- koncept/chapter13-5.tex
- koncept/chapter14-3.tex
- koncept/chapter3-10.tex
- koncept/chapter3-6.tex
- koncept/foreword.tex
Blandade korrekturändringar 5 april 2018.
> Korrekturändringar 5/4 -18

- koncept/chapter3-6.tex
- koncept/chapter3-7.tex
> Korrigeringar kapitel 3.6 och 3.7

- koncept/chapter15-1.tex
> Ändrat rubrik 15.1 till Att föra loggbok Fixes #428

- koncept/chapter3-5.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
> Mindre korrigeringar kapitel 3.8

- koncept/chapter1-7.tex
Fixa till rubriken till 1.7.1.
Fixes #423
> Fixa till rubrik 1.7.1

- koncept/chapter3-2.tex
- koncept/common.tex
Flytta undantag för avstavning till egen ordlista.
Fixes #431. Fixes #412.
> Flytta avstavning till ordlista

- koncept/appendix-n.tex
> Förtydling, justering efter möte med provförrättare

- koncept/chapter3-9.tex
- koncept/common.tex
> Mindre korrigeringar kapitel 3.9

- koncept/chapter1-1.tex
- koncept/chapter1-3.tex
- koncept/chapter1-4.tex
- koncept/chapter1-7.tex
- koncept/chapter9-1.tex
- koncept/foreword.tex
Små korrekturändringar och lite till. Kan någon kolla så minustecknen (Unicode) renderas rätt?
> Korrektur mm 13/8 -18

- BUILD.md
- CHANGELOG.md
- koncept/chapter1-1.tex
- koncept/chapter1-3.tex
- koncept/chapter1-4.tex
- koncept/chapter2-3.tex
- texifiering.md
Fixa till minustecken som inte renderades korrekt efter #439 
Och gör dokumentationen lite snyggare.
Inga.
> Gör några minustecken synliga igen

- koncept/common.tex
- Numrera innehållsförteckningen i PDF:en
Fixes #447
> Numrera innehållsförteckningen i PDF:en

- lectures/Elsäkerhet.tex
> Skapat lektion om elsäkerhet

- .travis.yml
Bygg projektet med (nyare) Ubuntu 18.04 Bionic på Travis CI.
Nej, inga.
> Bygg med Ubuntu Bionic

- koncept/chapter1-5.tex
Rätta koden så den kan byggas.
Nej, inga.
> Åtgärda byggfel

- Dockerfile
Uppgradera till att använda Linux Alpine 3.10 inuti Docker-containern vid bygge.
Nej, inga.
> Uppgradera till Linux Alpine 3.10

- README.md
- koncept/appendix-a.tex
- koncept/appendix-c.tex
- koncept/appendix-f.tex
- koncept/chapter1-1.tex
- koncept/chapter1-10.tex
- koncept/chapter1-5.tex
- koncept/chapter1-6.tex
- koncept/chapter1-7.tex
- koncept/chapter1-8.tex
- koncept/chapter11-1.tex
- koncept/chapter12-2.tex
- koncept/chapter2-1.tex
- koncept/chapter2-2.tex
- koncept/chapter2-3.tex
- koncept/chapter2-4.tex
- koncept/chapter2-5.tex
- koncept/chapter3-1.tex
- koncept/chapter3-3.tex
- koncept/chapter3-6.tex
- koncept/chapter3-7.tex
- koncept/chapter4-1.tex
- koncept/chapter5-2.tex
- koncept/chapter5-8.tex
- koncept/chapter6-1.tex
- koncept/chapter6-2.tex
- koncept/chapter7-1.tex
- koncept/chapter8-5.tex
- koncept/chapter8-7.tex
- texifiering.md
Blandade ändringar 2019-09-22.
Nej, inga.
> Blandade ändringar 22/9 -19

- koncept/appendix-g.tex
- koncept/appendix-i.tex
- koncept/chapter1-8.tex
- koncept/chapter10-4.tex
- koncept/chapter11-1.tex
- koncept/chapter12-2.tex
- koncept/chapter13-5.tex
- koncept/chapter3-5.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
- koncept/chapter5-2.tex
- koncept/chapter5-3.tex
- koncept/chapter5-6.tex
- koncept/chapter5-9.tex
- koncept/chapter6-1.tex
- koncept/chapter6-2.tex
- koncept/chapter7-1.tex
- koncept/chapter7-3.tex
- koncept/chapter8-6.tex
- koncept/chapter8-7.tex
- koncept/common.tex
Blandade ändringar 2019-09-25.
Nej, inga.
> Blandat 25/9 -19

- koncept/appendix-c.tex
- koncept/chapter1-1.tex
- koncept/chapter1-2.tex
- koncept/chapter1-5.tex
- koncept/chapter2-1.tex
- koncept/chapter2-10.tex
- koncept/chapter2-2.tex
- koncept/chapter2-7.tex
- koncept/chapter3-1.tex
- koncept/chapter3-4.tex
- koncept/chapter3-7.tex
- koncept/chapter5-2.tex
- koncept/chapter5-6.tex
- koncept/chapter5-9.tex
- koncept/chapter6-1.tex
- koncept/common.tex
Använd siunitx på några ställen, gör bland annat så att en del enheter inte längre är kursiverade.
Nej, inga.
> Använd siunitx på några ställen

- koncept.tex
- koncept/chapter1-6.tex
- koncept/chapter1-8.tex
- koncept/chapter2-1.tex
- koncept/chapter2-3.tex
- koncept/chapter3-1.tex
- koncept/chapter3-10.tex
- koncept/chapter3-2.tex
- koncept/chapter5-2.tex
- koncept/chapter5-3.tex
- koncept/chapter5-8.tex
- koncept/chapter5-9.tex
- koncept/chapter7-1.tex
- koncept/chapter7-6.tex
- texifiering.md
Lite blandat. Titta på ändringarna!
Nej, inga.
> Blandat 1/10 -19

- README.md
- koncept/appendix-a.tex
- koncept/appendix-i.tex
- koncept/chapter1-1.tex
- koncept/chapter1-10.tex
- koncept/chapter1-6.tex
- koncept/chapter1-8.tex
- koncept/chapter1-9.tex
- koncept/chapter11-1.tex
- koncept/chapter12-1.tex
- koncept/chapter12-3.tex
- koncept/chapter13-1.tex
- koncept/chapter13-4.tex
- koncept/chapter13-5.tex
- koncept/chapter14-2.tex
- koncept/chapter2-2.tex
- koncept/chapter2-3.tex
- koncept/chapter2-6.tex
- koncept/chapter2-8.tex
- koncept/chapter3-1.tex
- koncept/chapter5-9.tex
- koncept/chapter7-1.tex
- koncept/chapter7-6.tex
- koncept/chapter8-3.tex
- koncept/chapter8-5.tex
- koncept/chapter8-7.tex
- koncept/chapter9-1.tex
- Blandade förändringar, kolla på respektive commit.
> Blandat 2/10 -19

- koncept/foreword.tex
En merge conflict hade blivit kvar i förordet. Tas bort med denna ändring.
Nej, inga.
> Åtgärda merge conflict i foreword.tex

- koncept/appendix-h.tex
- koncept/chapter13-5.tex
> 2020:5 fix

- BUILD.md
- RELEASE.md
- SHA.txt
- koncept.tex
- koncept/chapter1-8.tex
- koncept/chapter2-6.tex
- koncept/chapter2-9.tex
- koncept/chapter8-3.tex
- koncept/foreword.tex
- koncept/tryckort.tex
- textbook.sty
Blandade ändringar. Se respektive fil eller commit.
> Blandade ändringar 6/1 -22

- koncept.tex
- koncept/appendix-v1litteratur.tex
- koncept/chapter2-2.tex
- koncept/chapter8-6.tex
> Mixed issues

- .gitignore
- Makefile
Det hade smugit sig in ett fel som gjorde att det inte gick att bygga lokalt.
> Fixa lokalt bygge

- koncept/chapter1-8.tex
> Fix typo in chapter1-8.tex

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/bygg.yml
- .github/workflows/länkar.yml
Boken och projektet innehåller ett antal hyperlänkar och webbadresser. Den här ändringen lägger till ett test i GitHub Actions som en gång i månaden letar upp adresser och testar så att de fungerar.
> Testa länkar

- .github/dependabot.yml
Aktivera versionsuppgraderingar med GitHub [Dependabot](https://docs.github.com/en/code-security/dependabot).
> Aktivera Dependabot

- koncept/tryckort.tex
> Uppdatera tryckinfo

- CHANGELOG.md
- koncept.bib
- koncept/appendix-frekvensplan.tex
- koncept/chapter10-1.tex
- koncept/chapter13-5.tex
- koncept/chapter13-6.tex
- koncept/chapter14-3.tex
Fixes #616 uppdatering av lag, förordning och PTS föreskrifter
> Uppdatering hänvisningar lag

- CHANGELOG.md
- koncept/chapter6-2.tex
Förbättring av texterna om simplex och halvduplex. Fix #643
> Förbättring av texterna om simplex och halvduplex

- koncept/chapter13-5.tex
Väldigt liten ändring, lägger till ett borttappat `för`
> lägg till borttappat för

- .github/dependabot.yml
- CHANGELOG.md
- koncept/appendix-beskrivningskoder.tex
- koncept/chapter1-10.tex
- koncept/chapter1-4.tex
- koncept/chapter1-8.tex
- koncept/chapter10-4.tex
- koncept/chapter2-1.tex
- koncept/chapter2-2.tex
- koncept/chapter2-3.tex
- koncept/chapter2-5.tex
- koncept/chapter3-1.tex
- koncept/chapter4-1.tex
- koncept/chapter6-1.tex
- koncept/inkludera-kapitel.tex
- koncept/introduction.tex
Fix #668 och fix #664. Börjar på #604.
> Blandat 26/9 -23

- koncept/chapter13-5.tex
> Fixa till parenteserna och KN

- .github/workflows/bygg.yml
- CHANGELOG.md
- koncept/chapter1-9.tex
- koncept/inkludera-kapitel.tex
- Fixa avsnittsnivåerna i kapitel 1 Ellära. Fix #644
> Fixa avsnittsnivåerna i kapitel 1 Ellära

- CHANGELOG.md
- koncept.bib
Formatförbättringar i referenslistan. Några posters årtal uppdaterade. Relaterat till #550.
> Formatförbättringar referenslistan

- .devcontainer/devcontainer.json
- .github/dependabot.yml
- BUILD.md
- CHANGELOG.md
- Dockerfile
- koncept/chapter2-1.tex
- koncept/chapter2-10.tex
- koncept/chapter2-2.tex
- koncept/chapter2-7.tex
- koncept/chapter2-9.tex
- koncept/chapter3-1.tex
- koncept/chapter3-2.tex
- koncept/chapter3-5.tex
- koncept/chapter5-9.tex
- koncept/chapter6-2.tex
- koncept/chapter8-3.tex
- koncept/foreword.tex
Blandade ändringar 2024-01-17.
- Ta bort texten om integrationsgrad. Fix #690 
- Ta bort ett delavsnitt som var sammanfattning, och infoga del av texten i delavsnittet före. Fix #374 
- Ersätt Ursigram med Vågutbredningsprognoser. Fix #651 
- Lägg till konfiguration av devcontainer för de som använder Visual Studio Code, lokalt eller på GitHub.
> Blandat 17/1 -24

- koncept.tex
- koncept/chapter1-1.tex
- koncept/chapter1-5.tex
- koncept/chapter11-1.tex
- koncept/chapter13-5.tex
- koncept/chapter2-1.tex
- koncept/chapter2-2.tex
- koncept/chapter2-3.tex
- koncept/chapter2-7.tex
- koncept/chapter5-2.tex
- koncept/chapter5-3.tex
- koncept/chapter5-6.tex
- koncept/chapter5-9.tex
- koncept/chapter6-1.tex
- koncept/chapter7-1.tex
- koncept/matte.tex
Lägg (räkne-) exempel i rutor, med hjälp av [tcolorbox](https://ctan.org/pkg/tcolorbox).
> Lägg räkneexempel i rutor

- .github/workflows/webbadresser.yml
- Dockerfile
- texifiering.md
Lite teknisk fix. Se respektive commit.
> Lite teknisk fix

- koncept/appendix-lashanvisningar.tex
- koncept/chapter3-10.tex
- koncept/chapter3-2.tex
- Rätta en korsreferens till avsnittet DSP.
> Rätta en korsreferens till avsnittet DSP

- README.md
- koncept/chapter1-4.tex
- koncept/chapter1-6.tex
- koncept/chapter1-7.tex
- koncept/chapter10-2.tex
- koncept/chapter10-4.tex
- koncept/chapter13-4.tex
- koncept/chapter2-1.tex
- koncept/chapter2-4.tex
- koncept/chapter2-5.tex
- koncept/chapter2-6.tex
- koncept/chapter2-9.tex
- koncept/chapter3-1.tex
- koncept/chapter3-10.tex
- koncept/chapter3-6.tex
- koncept/chapter3-7.tex
- koncept/chapter3-8.tex
- koncept/chapter3-9.tex
- koncept/chapter4-1.tex
- koncept/chapter5-2.tex
- koncept/chapter5-8.tex
- koncept/chapter5-9.tex
- koncept/chapter7-6.tex
- koncept/chapter9-2.tex
- koncept/mottagare.tex
Blandade ändringar 2024-03-02. Se respektive commit.
> Blandat 2/3 -24

- CHANGELOG.md
- koncept/ellaera.tex
Med hjälp av @SM7NTJ och Bing Chat kommer här en ny introduktion till kapitlet Ellära. Fix #605
> Ny introduktion till kapitlet Ellära

- CHANGELOG.md
- README.md
- koncept/appendix-mattenheter.tex
- koncept/chapter1-2.tex
- koncept/chapter1-8.tex
- koncept/chapter10-3.tex
- koncept/chapter10-4.tex
- koncept/chapter11-1.tex
- koncept/chapter12-1.tex
- koncept/chapter12-2.tex
- koncept/chapter13-2.tex
- koncept/chapter13-6.tex
- koncept/chapter14-3.tex
- koncept/chapter2-1.tex
- koncept/chapter2-2.tex
- koncept/chapter2-3.tex
- koncept/chapter2-4.tex
- koncept/chapter3-2.tex
- koncept/chapter3-3.tex
- koncept/chapter3-4.tex
- koncept/chapter3-6.tex
- koncept/chapter3-7.tex
- koncept/chapter5-8.tex
- koncept/chapter6-1.tex
- koncept/chapter7-1.tex
- koncept/chapter7-5.tex
- koncept/chapter7-6.tex
- koncept/chapter8-7.tex
- koncept/komponenter.tex
- koncept/kretsar.tex
- Blandat innehåll, se respektive commit.
- Fix #675 
- Fix #677
> Blandat 6/4 -24

- CHANGELOG.md
- koncept.tex
- koncept/foerord.tex
- Lägg till QR-koder för återkoppling i förordet.
> Lägg till QR-koder för återkoppling i förordet

- .github/workflows/bygg.yml
- Dockerfile
Uppgradera byggmiljö till Ubuntu 24.04. Fix #728
> Uppgradera byggmiljö till Ubuntu 24.04

- CHANGELOG.md
- koncept.bib
- koncept/chapter12-1.tex
Flytta ref till broschyr om elolycka till litteraturlistan samt rätta till namnet.
> Flytta ref till broschyr om elolycka till litteraturlistan

- CHANGELOG.md
- koncept/appendix-frekvensplan.tex
Gör kolumnen högeffekt tydligare. Fix #741
> Gör kolumnen högeffekt tydligare

- koncept/kretsar-filter.tex
> Rätta stavningen på engelska filter
